## Queries

query CurrentIdentity {
  currentIdentity {
    id
    role
    token
    email
    firstName
    lastName
  }
}

## Mutations

mutation CreateGuest {
  createGuest {
    token
  }
}

## Fragments

# fragment Timestamps on Identity {
#   updatedAt
#   createdAt
# }
