## Queries

query ShowCurrentUser {
  currentUser {
    id
    role
    token
    email
    firstName
    lastName
  }
}

## Mutations

mutation CreateAnonymousUser {
  createAnonymousUser {
    token
  }
}

## Fragments

# fragment Timestamps on User {
#   updatedAt
#   createdAt
# }
